[package]
name = "ARC8004"
version = "1.0.0"
authors = ["Aptos-x402 Team"]

[addresses]
# Module address - set to admin address for fresh deployments
# If redeploying, this will be the admin account address: 0xa4d7e1f47887dc6b84743297164fdd63deaa872329f8617be1d4c87375d39323
arc8004 = "0xa4d7e1f47887dc6b84743297164fdd63deaa872329f8617be1d4c87375d39323"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-addresses]
arc8004 = "0xCAFE"

[dev-dependencies]

